### ISSUE TITLE
Разновидности архитектуры ПО и метки, связанные с ними

### ISSUE THREAD

**Issue by Konstantin-sdc** [Konstantin-sdc/GeneralDevelopmentRules#7]
### [Архитектура программного обеспечения](https://ru.wikipedia.org/wiki/Архитектура_программного_обеспечения) 

_Originally posted by @Konstantin-sdc in https://github.com/Konstantin-sdc/GeneralDevelopmentRules/issues/5#issuecomment-532262386_

**Нужно знать:**
- [ ] [Из каких частей состоит ПО, и как составные части ПО взаимодействуют друг с другом.](https://github.com/Konstantin-sdc/GeneralDevelopmentRules/issues/9)
- [ ] [Короткие названия и описания составных частей ПО.](https://github.com/Konstantin-sdc/GeneralDevelopmentRules/issues/10)
- [ ] [Как различаются варианты ПО по их составу из различных частей и компоновке этих частей.](https://github.com/Konstantin-sdc/GeneralDevelopmentRules/issues/11)
- [ ] [Короткие названия и описания вариантов состава и компоновки ПО.](https://github.com/Konstantin-sdc/GeneralDevelopmentRules/issues/13)

**Comment by Konstantin-sdc** [comment]
Это составной вопрос / задача. Чтобы его решить, нужно решить составляющие его вопросы.

**Comment by Konstantin-sdc** [comment]
Из каких частей состоит ПО, и как составные части ПО взаимодействуют друг с другом.

**Comment by Konstantin-sdc** [comment]
Короткие названия и описания составных частей ПО.

**Comment by Konstantin-sdc** [comment]
Как различаются варианты ПО по их составу из различных частей и компоновке этих частей.

**Comment by Konstantin-sdc** [comment]
Короткие названия и описания вариантов состава и компоновки ПО.
